language: php
sudo: false
cache:
  directories:
    - "$HOME/.composer/cache/files"
matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_install:
  - composer self-update
  - mkdir build
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - mv box.phar box
  - chmod 755 box

install:
  - composer install --no-dev
  - php box build
  - composer install
  - vendor/bin/phpcs --standard=psr2 ./src ./tests

script:
  - vendor/bin/phpunit

deploy:
  provider: releases
  api_key:
    secure: XzJTzl3BO0rOTBCCtnwlicdoBstZ0nK8pYpfz4OS+T3jK/bgzjNWd6UPRUP+QNdJ+AisYWscoIW4f9rgG1Ma5LODaNGacTAspEv83sS1S3Ye8XJfha4dwgXPhNggkdi88d/xcL7nwNyrP970HO+C5FYvga58pXs+4uE0yVd/HrbFcJHn9nlSeYzuCDCfif7KLsA86fdCEndVAUvmSsskZuS/79bZjNWDqA5sqRq9ns3KAyNPsO9Ftowf6f69dd2b3sv0hKxuk/5cIpu5qTFkQEdPZxkXODHQIOLVXxZW11NC2etBAWm5cuqWqTZp121rORwWBqTQd98+AkHMwwiGtBBb3hqQfiHs7/BNMRyiNPkJd5MfN9iVe75av0rpr69yag4AjdeCyyLLqOHMjVHKqZZz0IcobJx4HlyprjlGjFCRtdRCO3nTqqww0YqZkXToQ31m/t3tsOAkrKGlmREMiCJRo8SxR7lqolWcKpzxrVutA0DvpSvlzbEivW0ecN/mcbwIC518F8GpN/EG4jTEA6ZS6a0oRe3+GU8g/+Hc1ALkjyLAYK33zTLbvAuOCofhhBlFjEtc9wBnblTQAvAjjS6JUhpArLStjbMVHlJn6/mr+7fr7ZPxZEDzL7GWk+tJ/gHzdUckc7LFQw9S2zKFWGCjWfISC1MAN6C13lvTnEg=
  file: build/transmission-cli.phar
  skip_cleanup: true
  on:
    repo: popstas/transmission-cli
    php: '5.6'
    tags: true

after_script:
  - travis_retry php vendor/bin/coveralls
