#!/bin/bash
echo "generate CHANGELOG.md"
# before v0.5.0 commits was not in angular format
releases_from_5_0=$(git tag | grep '^v' | tac | grep -n "v0.5.0" | cut -d':' -f1)
conventional-changelog -p angular -i docs/CHANGELOG_before_5.1.md -o CHANGELOG.md -r "$releases_from_5_0"
echo "generate docs/commands.md"
bin/transmission-cli _docs > docs/commands.md
